language: java
jdk:
  - openjdk15
cache:
  directories:
  - $HOME/.m2
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - mvn -e jib:build -P deploy-docker
after_success:
  - bash <(curl -s https://codecov.io/bash)
